steps:
- name: "gcr.io/cloud-builders/docker"
  args:
  - "build"
  - "-t"
  - "us-central1-docker.pkg.dev/cc-matcher-v1/matcher/matcher-app:latest"
  - "-f"
  - "Dockerfile.app"
  - "."
images:
- "us-central1-docker.pkg.dev/cc-matcher-v1/matcher/matcher-app:latest"
