steps:
- name: "gcr.io/cloud-builders/docker"
  args:
  - "build"
  - "-t"
  - "us-central1-docker.pkg.dev/cc-matcher-v1/matcher/intake-web:latest"
  - "-f"
  - "services/intake_web/Dockerfile"
  - "."
images:
- "us-central1-docker.pkg.dev/cc-matcher-v1/matcher/intake-web:latest"
